### ISSUE TITLE
Errors when using Example Notebooks

### ISSUE THREAD

**Issue by clarasb** [deepesdl/ML-Toolkits#16]
Errors occurred when running the following notebooks. See screenshots for more details.

1. cube_insights.ipynb
![cube_insights](https://github.com/user-attachments/assets/3a67f2b1-41c2-4056-ad67-02f8fdb0c74d)

2. gapfilling_process.ipynb
![gapfilling](https://github.com/user-attachments/assets/0b19e683-17c8-4ebf-8c17-4f6795fb7a9a)

3. transfer_learning.ipynb
![transfer_learning](https://github.com/user-attachments/assets/d5d9ef13-bdcc-4f00-926f-b2e1da788f5a)

**Comment by JPeters92** [comment]
1. cube_insights module  (now insights): fix integrated into the get_insights function
2. helper function is now used correcly to create the according file.
3. No loss was assigned within the trainer class. The default loss value was update to None. Now this notebook contains the corresponding loss

**Comment by clarasb** [comment]
Thanks for looking into the Issues.
In the notebook `gapfilling_process.ipynb` there's an issue with the import of `ml4xcube.xr_plots`. I edited it and wrote a PR (#19).
