### ISSUE TITLE
Error when using Example Notebook

### ISSUE THREAD

**Issue by clarasb** [deepesdl/ML-Toolkits#17]
Error occurred when running the following notebook. See screenshots for more details.

use_case_lst_tensorflow_masked.ipynb

![error2](https://github.com/user-attachments/assets/573a08d6-d5f3-4fc7-8015-12f0f630a0f6)
![error1](https://github.com/user-attachments/assets/39b99f57-b990-4e3a-9a07-33644109e4fa)

**Comment by JPeters92** [comment]
model path cannot end with *.pth but must end with *.keras
The fix inlcuded into the according notebook.

**Comment by clarasb** [comment]
Perfect!
